apiVersion: v1
kind: Secret
metadata:
  name: awesomerag-secrets
  namespace: awesomerag
type: Opaque
stringData:
  rag_api: REPLACE_WITH_GROQ_KEY
  qd_api_key: REPLACE_WITH_QDRANT_API_KEY
  qd_url: https://1efe5184-73a3-4b29-b8ae-bd3e7e40a020.us-east-1-1.aws.cloud.qdrant.io:6333
